name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/primedecomp/build:main
    strategy:
      fail-fast: false
      matrix:
        version: [usa]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        python configure.py --map --version ${{matrix.version}} --compilers /compilers/GC
        ninja
    - name: Upload progress
      if: false # github.ref == 'refs/heads/main'
      continue-on-error: true
      env:
        PROGRESS_API_KEY: ${{secrets.PROGRESS_API_KEY}}
      run: |
        python tools/upload-progress.py -b https://progress.deco.mp/ -p prime -v ${{matrix.version}} \
          build/pikmin2.${{matrix.version}}/main.dol.progress
    - name: Upload map
      uses: actions/upload-artifact@v3
      with:
        name: pikmin2UP-${{matrix.version}}.MAP
        path: build/*/pikmin2UP.MAP
