name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/projectpiki/build:main
    strategy:
      fail-fast: false
      matrix:
        version: [GPVE01, GPVE01_D17]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Build
      run: |
        python configure.py -v ${{matrix.version}} --compilers /compilers/GC
        ninja
    - name: Upload progress
      if: github.ref == 'refs/heads/main'
      continue-on-error: true
      env:
        PROGRESS_API_KEY: ${{secrets.PROGRESS_API_KEY}}
      run: |
        python tools/upload-progress.py -b https://progress.decomp.club/ -p pikmin2 -v ${{matrix.version}} \
          build/pikmin2.${{matrix.version}}/main.dol.progress
    - name: Upload map
      uses: actions/upload-artifact@v4
      with:
        name: pikmin2UP-${{matrix.version}}.MAP
        path: build/*/pikmin2UP.MAP

  build_make:
    name: Build (legacy)
    runs-on: ubuntu-latest
    container: ghcr.io/projectpiki/build:main
    strategy:
      fail-fast: false
      matrix:
        version: [GPVE01, GPVE01_D17]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Build
      run: |
        python tools/download_tool.py dtk build/tools/dtk --tag v0.9.2
        python tools/download_tool.py sjiswrap build/tools/sjiswrap.exe --tag v1.1.1
        python tools/download_tool.py binutils build/binutils --tag 2.42-1
        python tools/download_tool.py wibo build/tools/wibo --tag 0.6.15
        python tools/download_tool.py compilers build/compilers --tag 20231018
        make -j$(nproc) MAPGENFLAG=1 VERSION=${{matrix.version}} COMPILERS=/compilers/GC
